# Generated by Django 3.2 on 2022-01-14 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_department_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='std',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='taskapp.student'),
        ),
    ]
